apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-1
spec:
  containers:
    - name: container-vol-1
      image: kai1114/hello
      volumeMounts:
        - name: empty-dir-1
          mountPath: /mount-1
  volumes:
    - name: empty-dir-1
      emptyDir: {}