apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-3
spec:
  containers:
    - name: container
      image: kai1114/hello
      volumeMounts:
        - name: pvc-pv
          mountPath: /mount-2
  volumes:
    - name: pvc-pv
      persistentVolumeClaim:
        claimName: pv-claim-1