apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-green
spec:
  replicas: 2
  selector:
    matchLabels:
      ver: v2
  template:
    metadata:
      labels:
        ver: v2
    spec:
      containers:
        - name: container-3
          image: kai1114/hello:v2