apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-1
  namespace: namespace-1
spec:
  limits:
    - type: Container
      min:
        memory: 0.1Gi
      max:
        memory: 1Gi
      defaultRequest:
        memory: 0.2Gi
      default:
        memory: 0.5Gi
      maxLimitRequestRatio:
        memory: "3"