apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  namespace: namespace-1
spec:
  containers:
    - name: container-1
      image: kai1114/hello
      resources:
        requests:
          memory: 0.1Gi
        limits:
          memory: 0.2Gi
