apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: liveness
spec:
  containers:
    - name: container-1
      image: kai1114/hello
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
  terminationGracePeriodSeconds: 0