apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: readiness
spec:
  containers:
    - name: container-1
      image: kai1114/hello
      ports:
        - containerPort: 8000
      readinessProbe:
        exec:
          command: [ "cat", "/readiness/ready.txt" ]
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 3
  terminationGracePeriodSeconds: 0