apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-2
spec:
  containers:
    - name: container-vol-1
      image: kai1114/hello
      volumeMounts:
        - name: host-path-1
          mountPath: /mount-1
    - name: container-vol-2
      image: kai1114/hello
      volumeMounts:
        - name: host-path-1
          mountPath: /mount-2
  volumes:
    - name: host-path-1
      hostPath:
        path: /node-path
        type: Directory